[package]
name = "pixel-sort"
version = "0.1.0"
edition = "2024"
description = "A GPU implementation of the pixel sort procedural art technique"
readme = "README.md"
homepage = "https://github.com/tomBoddaert/PixelSort/"
license = "MIT OR Apache-2.0"
keywords = ["gpu", "art", "image"]
categories = ["algorithms", "graphics", "multimedia::images"]
exclude = ["/examples/source*.jpg", "comparison.png"]

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
image = "0.25.10"
wgpu = "30.0.0"

[dev-dependencies]
eframe = "0.36.1"
env_logger = "0.11.11"
pollster = "1.0.1"
rfd = "0.17.2"
winit = "0.30.13"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
# Groups
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }

allow_attributes = "warn"
get_unwrap = "warn"
panic_in_result_fn = "warn"
pub_without_shorthand = "warn"
redundant_type_annotations = "warn"
todo = "warn"
cognitive_complexity = "warn"
unwrap_used = "warn"
